ORDINALES_MASCULINO = (
    "primer",
    "segundo",
    "tercer",
    "cuarto",
    "quinto",
    "sexto",
    "séptimo",
    "octavo",
    "noveno",
    "décimo",
    "undécimo",
    "duodécimo",
    "decimotercero",
    "decimocuarto",
    "decimoquinto",
    "decimosexto",
    "decimoséptimo",
    "decimoctavo",
    "decimonoveno",
    "vigésimo",
    "vigésimo primer",
    "vigésimo segundo",
    "vigésimo tercer",
    "vigésimo cuarto",
    "vigésimo quinto",
    "vigésimo sexto",
    "vigésimo séptimo",
    "vigésimo octavo",
    "vigésimo noveno",
    "trigésimo",
)

ORDINALES_FEMENINO = (
    "primera",
    "segunda",
    "tercera",
    "cuarta",
    "quinta",
    "sexta",
    "séptima",
    "octava",
    "novena",
    "décima",
    "undécima",
    "duodécima",
    "decimotercera",
    "decimocuarta",
    "decimoquinta",
    "decimosexta",
    "decimoséptima",
    "decimoctava",
    "decimonovena",
    "vigésima",
    "vigésima primera",
    "vigésima segunda",
    "vigésima tercera",
    "vigésima cuarta",
    "vigésima quinta",
    "vigésima sexta",
    "vigésima séptima",
    "vigésima octava",
    "vigésima novena",
    "trigésima",
)
